### ISSUE TITLE
Docker trigger support

### ISSUE THREAD

**Issue by andrein** [jgramoll/terraform-provider-spinnaker#32]
Hi, 

I'd like to contribute docker trigger support. 
Right now, it looks like the provider only supports jenkins, and some jenkins specific fields are required(job, master). 
I could add new fields for docker to the existing resource and make the jenkins fields optional, however this would make it harder to validate the resource. 
Another option would be to rename the current resource to spinnaker_pipeline_jenkins_trigger and add a new resource spinnaker_pipeline_docker_trigger, but this change wouldn't be backwards compatible.

Any thoughts on this?

Thanks,
Andrei

**Comment by jgramoll** [comment]
Yeah. I am working on a patch set to add a deprecation on spinnaker_pipeline_trigger and keep add spinnaker_pipeline_jenkins_trigger, spinnaker_pipeline_docker_trigger as additional resources

**Comment by jgramoll** [comment]
Can you help me know what the json body for docker trigger should look like?

**Comment by andrein** [comment]
Hi @jgramoll, the Docker trigger looks like this when created via the web interface: 
```
  "triggers": [
    {
      "account": "docker-hub",
      "enabled": true,
      "organization": "library",
      "registry": "index.docker.io",
      "repository": "library/nginx",
      "tag": "tag regex",
      "type": "docker"
    }
  ],
```

I've looked over the pull request and it looks like you don't add the `registry` field. Spinnaker seems to add it automatically when the pipeline is saved. We'll give the pull request a try and let you know how it goes.

**Comment by andrein** [comment]
We tried the code, it works as expected, however i've noticed a bug: if the pipeline has a manually defined docker trigger, the provider adds another one. This also happens for stage definitions. Have you encountered this before?

**Comment by jgramoll** [comment]
That is expected behavior. If you already have a stage / trigger that you want to export as terraform you need to use `terraform import spinnaker_pipeline_docker_trigger ${pipelineId}_${triggerId}`

**Comment by jgramoll** [comment]
Let me know if you still have a problem
