### ISSUE TITLE
Thanks for the provider but i have problem when i want to provision template and template_config

### ISSUE THREAD

**Issue by vdmaxi4** [jgramoll/terraform-provider-spinnaker#82]
Error: Provider produced inconsistent result after apply

When applying changes to spinnaker_pipeline_template.terraform_example,
provider "local/providers/spinnaker" produced an unexpected new value: Root
resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

**Comment by jgramoll** [comment]
Do you have the terraform you are trying to apply?

**Comment by vdmaxi4** [comment]
oh sorry! yes i have terraform ver 0.13.5 )

**Comment by jgramoll** [comment]
yes, what are the terraform resources you are trying to apply. example: 

```
resource "spinnaker_pipeline" "main" {
  application = "myapp"
  name        = "My New Pipeline"
}
```

**Comment by vdmaxi4** [comment]
data "template_file" "dcd_template" {
  template = file("pipelines/template-check-v2.json")
}

resource "spinnaker_pipeline_template" "terraform_example" {
  template = data.template_file.dcd_template.rendered
}

data "template_file" "dcd_template_config" {
  template = file("pipelines/gke-check-config.json")
}

resource "spinnaker_pipeline_template_config" "terraform_example" {
  pipeline_config = data.template_file.dcd_template_config.rendered
}

**Comment by jgramoll** [comment]
Are you sure you are using this provider. It doesn't currently support those resource types. We could add them, but currently it should be saying 
```
The provider provider.spinnaker does not support resource type
"spinnaker_pipeline_template".
```

**Comment by vdmaxi4** [comment]
oh soorry! maybe i was confused and i tried several spinnaker-provides! and error was from this provider https://github.com/armory-io/terraform-provider-spinnaker 
but would be good if you have this feature )

**Comment by vdmaxi4** [comment]
i added issues as well  :)
i will close this issue
